FROM node:18 as build

MAINTAINER SDF Ops Team <ops@stellar.org>

WORKDIR /app

COPY ./packages/lumenswap.io/ /app/
RUN yarn install

# Build the Next.js application
RUN yarn build

# Expose the port Next.js app is running on
EXPOSE 3000

# Command to run the Next.js application
CMD ["yarn", "run", "dev"]