version: "3.8"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
      - "8000:80"
  lumenswap:
    build:
      context: .
      dockerfile: Dockerfile-lumenswap
    ports:
      - "3000:3000"
